2025-05-10 15:38:43,833 | INFO | üìÑ Starting processing file: 2025 - 01 - 01- Night Audit Packet.pdf
2025-05-10 15:38:43,865 | INFO | üìÑ Starting processing file: 2025 - 01 - 02- Night Audit Packet.pdf
2025-05-10 15:38:43,873 | INFO | üìÑ Starting processing file: 2025 - 01 - 03- Night Audit Packet.pdf
2025-05-10 15:38:43,886 | INFO | üìÑ Starting processing file: 2025 - 01 - 04- Night Audit Packet.pdf
2025-05-10 15:38:43,900 | INFO | üìÑ Starting processing file: 2025 - 01 - 05- Night Audit Packet.pdf
2025-05-10 15:38:43,919 | INFO | üìÑ Starting processing file: 2025 - 01 - 06- Night Audit Packet.pdf
2025-05-10 15:38:43,923 | INFO | üìÑ Starting processing file: 2025 - 01 - 07- Night Audit Packet.pdf
2025-05-10 15:38:43,975 | INFO | üìÑ Starting processing file: 2025 - 01 - 08- Night Audit Packet.pdf
2025-05-10 15:38:58,912 | ERROR | ‚ùå A/R Aging extraction failed: name 'is_strictly_numeric' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in extract_ar_aging
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in <genexpr>
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
NameError: name 'is_strictly_numeric' is not defined

2025-05-10 15:38:58,919 | ERROR | ‚ùå Transaction Closeout extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 61, in handle_section
    if clean_map: df = clean_column_names(df, clean_map)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:38:58,932 | ERROR | ‚ùå In-House List extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 105, in extract_inhouse_df
    df["arrive"] = df["arrive"].apply(convert_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:38:58,942 | ERROR | ‚ùå room_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:38:58,943 | ERROR | ‚ùå performance_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:38:58,945 | ERROR | ‚ùå guest_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:38:58,946 | ERROR | ‚ùå Ledger Activity extraction failed: name 'extract_amount' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 172, in extract_ledger_activity_report_with_metadata
    current_entry['opening_balance'] = extract_amount(re.search(r'-?\(?[\d,.]+\)?', line).group(0))
NameError: name 'extract_amount' is not defined

2025-05-10 15:39:00,233 | ERROR | ‚ùå A/R Aging extraction failed: name 'is_strictly_numeric' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in extract_ar_aging
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in <genexpr>
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
NameError: name 'is_strictly_numeric' is not defined

2025-05-10 15:39:00,234 | ERROR | ‚ùå Transaction Closeout extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 61, in handle_section
    if clean_map: df = clean_column_names(df, clean_map)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:00,237 | ERROR | ‚ùå In-House List extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 105, in extract_inhouse_df
    df["arrive"] = df["arrive"].apply(convert_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:00,252 | ERROR | ‚ùå room_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,253 | ERROR | ‚ùå performance_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,254 | ERROR | ‚ùå guest_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,262 | ERROR | ‚ùå Ledger Activity extraction failed: name 'extract_amount' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 172, in extract_ledger_activity_report_with_metadata
    current_entry['opening_balance'] = extract_amount(re.search(r'-?\(?[\d,.]+\)?', line).group(0))
NameError: name 'extract_amount' is not defined

2025-05-10 15:39:00,677 | ERROR | ‚ùå A/R Aging extraction failed: name 'is_strictly_numeric' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in extract_ar_aging
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in <genexpr>
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
NameError: name 'is_strictly_numeric' is not defined

2025-05-10 15:39:00,679 | ERROR | ‚ùå Transaction Closeout extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 61, in handle_section
    if clean_map: df = clean_column_names(df, clean_map)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:00,682 | ERROR | ‚ùå In-House List extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 105, in extract_inhouse_df
    df["arrive"] = df["arrive"].apply(convert_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:00,687 | ERROR | ‚ùå room_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,688 | ERROR | ‚ùå performance_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,692 | ERROR | ‚ùå guest_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,693 | ERROR | ‚ùå Ledger Activity extraction failed: name 'extract_amount' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 172, in extract_ledger_activity_report_with_metadata
    current_entry['opening_balance'] = extract_amount(re.search(r'-?\(?[\d,.]+\)?', line).group(0))
NameError: name 'extract_amount' is not defined

2025-05-10 15:39:00,776 | ERROR | ‚ùå A/R Aging extraction failed: name 'is_strictly_numeric' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in extract_ar_aging
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in <genexpr>
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
NameError: name 'is_strictly_numeric' is not defined

2025-05-10 15:39:00,779 | ERROR | ‚ùå Transaction Closeout extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 61, in handle_section
    if clean_map: df = clean_column_names(df, clean_map)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:00,846 | ERROR | ‚ùå In-House List extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 105, in extract_inhouse_df
    df["arrive"] = df["arrive"].apply(convert_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:00,861 | ERROR | ‚ùå room_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,863 | ERROR | ‚ùå performance_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,864 | ERROR | ‚ùå guest_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:00,865 | ERROR | ‚ùå Ledger Activity extraction failed: name 'extract_amount' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 172, in extract_ledger_activity_report_with_metadata
    current_entry['opening_balance'] = extract_amount(re.search(r'-?\(?[\d,.]+\)?', line).group(0))
NameError: name 'extract_amount' is not defined

2025-05-10 15:39:01,118 | ERROR | ‚ùå A/R Aging extraction failed: name 'is_strictly_numeric' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in extract_ar_aging
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in <genexpr>
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
NameError: name 'is_strictly_numeric' is not defined

2025-05-10 15:39:01,120 | ERROR | ‚ùå Transaction Closeout extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 61, in handle_section
    if clean_map: df = clean_column_names(df, clean_map)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:01,123 | ERROR | ‚ùå In-House List extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 105, in extract_inhouse_df
    df["arrive"] = df["arrive"].apply(convert_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:01,130 | ERROR | ‚ùå room_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,131 | ERROR | ‚ùå performance_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,131 | ERROR | ‚ùå guest_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,133 | ERROR | ‚ùå Ledger Activity extraction failed: name 'extract_amount' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 172, in extract_ledger_activity_report_with_metadata
    current_entry['opening_balance'] = extract_amount(re.search(r'-?\(?[\d,.]+\)?', line).group(0))
NameError: name 'extract_amount' is not defined

2025-05-10 15:39:01,422 | ERROR | ‚ùå A/R Aging extraction failed: name 'is_strictly_numeric' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in extract_ar_aging
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in <genexpr>
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
NameError: name 'is_strictly_numeric' is not defined

2025-05-10 15:39:01,426 | ERROR | ‚ùå Transaction Closeout extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 61, in handle_section
    if clean_map: df = clean_column_names(df, clean_map)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:01,429 | ERROR | ‚ùå In-House List extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 105, in extract_inhouse_df
    df["arrive"] = df["arrive"].apply(convert_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:01,436 | ERROR | ‚ùå room_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,437 | ERROR | ‚ùå performance_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,440 | ERROR | ‚ùå guest_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,440 | ERROR | ‚ùå Ledger Activity extraction failed: name 'extract_amount' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 172, in extract_ledger_activity_report_with_metadata
    current_entry['opening_balance'] = extract_amount(re.search(r'-?\(?[\d,.]+\)?', line).group(0))
NameError: name 'extract_amount' is not defined

2025-05-10 15:39:01,759 | ERROR | ‚ùå A/R Aging extraction failed: name 'is_strictly_numeric' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in extract_ar_aging
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in <genexpr>
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
NameError: name 'is_strictly_numeric' is not defined

2025-05-10 15:39:01,761 | ERROR | ‚ùå Transaction Closeout extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 61, in handle_section
    if clean_map: df = clean_column_names(df, clean_map)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:01,767 | ERROR | ‚ùå In-House List extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 105, in extract_inhouse_df
    df["arrive"] = df["arrive"].apply(convert_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:01,770 | ERROR | ‚ùå room_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,771 | ERROR | ‚ùå performance_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,771 | ERROR | ‚ùå guest_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:01,772 | ERROR | ‚ùå Ledger Activity extraction failed: name 'extract_amount' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 172, in extract_ledger_activity_report_with_metadata
    current_entry['opening_balance'] = extract_amount(re.search(r'-?\(?[\d,.]+\)?', line).group(0))
NameError: name 'extract_amount' is not defined

2025-05-10 15:39:02,831 | ERROR | ‚ùå A/R Aging extraction failed: name 'is_strictly_numeric' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in extract_ar_aging
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 53, in <genexpr>
    if re.fullmatch(r"\d+", account) and all(is_strictly_numeric(val) for val in numeric_tail):
NameError: name 'is_strictly_numeric' is not defined

2025-05-10 15:39:02,834 | ERROR | ‚ùå Transaction Closeout extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 61, in handle_section
    if clean_map: df = clean_column_names(df, clean_map)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:02,836 | ERROR | ‚ùå In-House List extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 105, in extract_inhouse_df
    df["arrive"] = df["arrive"].apply(convert_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:02,859 | ERROR | ‚ùå room_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:02,861 | ERROR | ‚ùå performance_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:02,862 | ERROR | ‚ùå guest_statistics extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:02,864 | ERROR | ‚ùå Ledger Activity extraction failed: name 'extract_amount' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 172, in extract_ledger_activity_report_with_metadata
    current_entry['opening_balance'] = extract_amount(re.search(r'-?\(?[\d,.]+\)?', line).group(0))
NameError: name 'extract_amount' is not defined

2025-05-10 15:39:04,513 | ERROR | ‚ùå Ledger Summary extraction failed: name 'add_metadata' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 63, in handle_section
    df = add_metadata(df, prop_code, user_id, report_date, business_date)
NameError: name 'add_metadata' is not defined

2025-05-10 15:39:04,546 | WARNING | ‚ö†Ô∏è No No Show Report data in 2025 - 01 - 01- Night Audit Packet.pdf
2025-05-10 15:39:04,550 | ERROR | ‚ùå Rate Discrepancy extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 196, in <lambda>
    "Rate Discrepancy", lambda _: extract_rate_discrepancy_wrapper({
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 115, in extract_rate_discrepancy_wrapper
    records = extract_rate_discrepancy(full_text_or_pages["page_texts"])
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 384, in extract_rate_discrepancy
    converted_start_date = convert_date(start_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:04,656 | ERROR | ‚ùå Hotel Journal Summary extraction failed: name 'safe_float' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 471, in extract_hotel_journal_summary
    df[col] = df[col].apply(lambda x: safe_float(x) if pd.notnull(x) else None)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 4753, in apply
    return SeriesApply(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/apply.py", line 1207, in apply
    return self.apply_standard()
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/apply.py", line 1287, in apply_standard
    mapped = obj._map_values(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
  File "lib.pyx", line 2920, in pandas._libs.lib.map_infer
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 471, in <lambda>
    df[col] = df[col].apply(lambda x: safe_float(x) if pd.notnull(x) else None)
NameError: name 'safe_float' is not defined

2025-05-10 15:39:04,657 | WARNING | ‚ö†Ô∏è No Hotel Journal Summary data in 2025 - 01 - 01- Night Audit Packet.pdf
2025-05-10 15:39:04,669 | ERROR | ‚ùå Hotel Journal Detail extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 57, in handle_section
    df = extract_func(list_of_pages) if list_of_pages else extract_func(full_text)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 212, in <lambda>
    lambda pages: extract_hotel_journal_details(pages).assign(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 5012, in assign
    data[k] = com.apply_if_callable(v, data)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/common.py", line 379, in apply_if_callable
    return maybe_callable(obj, **kwargs)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 213, in <lambda>
    date=lambda df: df["date"].apply(convert_date),
NameError: name 'convert_date' is not defined

2025-05-10 15:39:04,671 | ERROR | ‚ùå Reservation Activity extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 90, in handle_custom_section
    df = clean_column_names(df)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:04,671 | ERROR | ‚ùå Shift Reconciliation extraction failed: name 'convert_date' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 78, in handle_custom_section
    result = extract_func()
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 239, in <lambda>
    lambda: extract_shift_reconciliation(pdf),
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 604, in extract_shift_reconciliation
    business_date = convert_date(raw_date)
NameError: name 'convert_date' is not defined

2025-05-10 15:39:04,683 | ERROR | ‚ùå Tax Exempt extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 90, in handle_custom_section
    df = clean_column_names(df)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:04,703 | ERROR | ‚ùå Gross Room Revenue extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 90, in handle_custom_section
    df = clean_column_names(df)
NameError: name 'clean_column_names' is not defined

2025-05-10 15:39:04,717 | ERROR | ‚ùå Revenue by Rate Code extraction failed for 2025 - 01 - 01- Night Audit Packet.pdf: name 'safe_float' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 857, in extract_revenue_by_rate_code
    df[col] = df[col].apply(lambda x: safe_float(x))
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 4753, in apply
    return SeriesApply(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/apply.py", line 1207, in apply
    return self.apply_standard()
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/apply.py", line 1287, in apply_standard
    mapped = obj._map_values(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
  File "lib.pyx", line 2920, in pandas._libs.lib.map_infer
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/extractors.py", line 857, in <lambda>
    df[col] = df[col].apply(lambda x: safe_float(x))
NameError: name 'safe_float' is not defined

2025-05-10 15:39:04,718 | WARNING | ‚ö†Ô∏è No Revenue by Rate Code data for revenue_by_rate_code in 2025 - 01 - 01- Night Audit Packet.pdf
2025-05-10 15:39:04,724 | ERROR | ‚ùå Advance Deposit Journal extraction failed: name 'clean_column_names' is not defined
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 90, in handle_custom_section
    df = clean_column_names(df)
NameError: name 'clean_column_names' is not defined

