2025-05-13 04:04:48,744 | INFO | üìÑ Starting processing file: 2025 - 01 - 04- Night Audit Packet.pdf
2025-05-13 04:04:48,744 | INFO | üìÑ Starting processing file: 2025 - 01 - 05- Night Audit Packet.pdf
2025-05-13 04:04:48,745 | INFO | üìÑ Starting processing file: 2025 - 01 - 03- Night Audit Packet.pdf
2025-05-13 04:04:48,745 | INFO | üìÑ Starting processing file: 2025 - 01 - 06- Night Audit Packet.pdf
2025-05-13 04:04:48,745 | INFO | üìÑ Starting processing file: 2025 - 01 - 01- Night Audit Packet.pdf
2025-05-13 04:04:48,745 | INFO | üìÑ Starting processing file: 2025 - 01 - 02- Night Audit Packet.pdf
2025-05-13 04:04:48,745 | INFO | üìÑ Starting processing file: 2025 - 01 - 07- Night Audit Packet.pdf
2025-05-13 04:04:48,751 | INFO | üìÑ Starting processing file: 2025 - 01 - 08- Night Audit Packet.pdf
2025-05-13 04:05:04,928 | ERROR | ‚ùå A/R Aging extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:05,923 | ERROR | ‚ùå A/R Aging extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:06,170 | ERROR | ‚ùå A/R Aging extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:06,276 | ERROR | ‚ùå A/R Aging extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:06,276 | ERROR | ‚ùå A/R Aging extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:06,338 | ERROR | ‚ùå A/R Aging extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:06,423 | ERROR | ‚ùå A/R Aging extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:06,819 | ERROR | ‚ùå A/R Aging extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:14,966 | ERROR | ‚ùå Transaction Closeout extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:15,959 | ERROR | ‚ùå Transaction Closeout extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:16,209 | ERROR | ‚ùå Transaction Closeout extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:16,312 | ERROR | ‚ùå Transaction Closeout extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:16,313 | ERROR | ‚ùå Transaction Closeout extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:16,359 | ERROR | ‚ùå Transaction Closeout extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:16,451 | ERROR | ‚ùå Transaction Closeout extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:16,860 | ERROR | ‚ùå Transaction Closeout extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:25,016 | ERROR | ‚ùå In-House List extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:25,995 | ERROR | ‚ùå In-House List extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:26,250 | ERROR | ‚ùå In-House List extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:26,342 | ERROR | ‚ùå In-House List extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:26,342 | ERROR | ‚ùå In-House List extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:26,378 | ERROR | ‚ùå In-House List extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:26,480 | ERROR | ‚ùå In-House List extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:26,905 | ERROR | ‚ùå In-House List extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:35,050 | ERROR | ‚ùå room_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:36,024 | ERROR | ‚ùå room_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:36,279 | ERROR | ‚ùå room_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:36,357 | ERROR | ‚ùå room_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:36,362 | ERROR | ‚ùå room_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:36,393 | ERROR | ‚ùå room_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:36,503 | ERROR | ‚ùå room_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:36,936 | ERROR | ‚ùå room_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:45,074 | ERROR | ‚ùå performance_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:46,071 | ERROR | ‚ùå performance_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:46,319 | ERROR | ‚ùå performance_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:46,387 | ERROR | ‚ùå performance_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:46,392 | ERROR | ‚ùå performance_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:46,416 | ERROR | ‚ùå performance_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:46,533 | ERROR | ‚ùå performance_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:46,970 | ERROR | ‚ùå performance_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:55,106 | ERROR | ‚ùå guest_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:56,110 | ERROR | ‚ùå guest_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:56,356 | ERROR | ‚ùå guest_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:56,413 | ERROR | ‚ùå guest_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:56,420 | ERROR | ‚ùå guest_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:56,474 | ERROR | ‚ùå guest_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:56,553 | ERROR | ‚ùå guest_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:05:57,008 | ERROR | ‚ùå guest_statistics extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:06:05,150 | ERROR | ‚ùå Ledger Activity extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:06:06,139 | ERROR | ‚ùå Ledger Activity extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:06:06,384 | ERROR | ‚ùå Ledger Activity extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:06:06,448 | ERROR | ‚ùå Ledger Activity extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:06:06,455 | ERROR | ‚ùå Ledger Activity extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:06:06,497 | ERROR | ‚ùå Ledger Activity extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:06:06,591 | ERROR | ‚ùå Ledger Activity extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

2025-05-13 04:06:07,033 | ERROR | ‚ùå Ledger Activity extraction failed: 'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/processor.py", line 92, in handle_section
    insert_dataframe(engine, df, table_name, filename)
  File "/Users/sandeepmalkanoor/Documents/Python/Night_Audit_DataEngineering_Project/night_audit_etl_pipeline/db_utils.py", line 56, in insert_dataframe
    df.to_sql(table_name, con=engine, if_exists='append', index=False)
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandeepmalkanoor/Documents/Python/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'

